name: PR Reviewer Update

on:
  pull_request:
    types:
      # When a PR gets first opened
      - opened
      # When a PR gets new commits (to check if new reviewers need to be added)
      - synchronize

# Ensures that only one deploy task per branch/environment will run at a time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  request:
    name: Update PR reviewers
    runs-on: ubuntu-latest

    steps:
      - name: Execute PR reviewer linter
        run: |
          TODO
      - name: Retrieve PR reviewers
        run: |
          echo "CUR_PR_REVIEWERS=$(cat ${{ github.workspace }}/TODO_INSERT_RELATIVE_FILE_PATH)" >> $GITHUB_ENV
      - name: Create PR review request
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr edit ${{ github.event.pull_request.html_url }} \
              --add-reviewer ${{env.CUR_PR_REVIEWERS}}